# ansible/playbooks/refresh_inventory.yaml
---
- hosts: localhost
  gather_facts: false
  tasks:
    - meta: refresh_inventory

    - name: Wait for EC2 hosts to become reachable
      ansible.builtin.wait_for_connection:
        timeout: 600
